# Generated by Django 2.1.2 on 2018-10-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitao_star', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=40, unique=True, verbose_name='unique product id')),
                ('name', models.CharField(max_length=200, verbose_name='Product name')),
                ('introduct', models.CharField(max_length=300, verbose_name='breaf introduct')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('image', models.CharField(max_length=200, verbose_name='图片')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='上次更新时间')),
                ('tags', models.IntegerField(default=0, verbose_name='tag')),
            ],
        ),
    ]
