# Generated by Django 2.1.2 on 2018-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitao_star', '0002_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='head_image',
            field=models.ImageField(default='/static/default_head.png', upload_to='productHeads', verbose_name='图片'),
        ),
    ]
