# Generated by Django 2.1.2 on 2018-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitao_star', '0003_auto_20181021_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='head_image',
            field=models.ImageField(upload_to='productHeads', verbose_name='图片'),
        ),
    ]
